import WaringSProblemVariantsCanonicalLaneLean.WaringAdmissibleClass
import WaringSProblemVariantsCanonicalLaneLean.BridgeLemmas
import WaringSProblemVariantsCanonicalLaneLean.GateLemmas
import WaringSProblemVariantsCanonicalLaneLean.FinalTheorem
import WaringSProblemVariantsCanonicalLaneLean.WaringMinorArcs
import WaringSProblemVariantsCanonicalLaneLean.WaringMajorArcs
import WaringSProblemVariantsCanonicalLaneLean.WaringEndpointClassification

namespace HautevilleHouse
namespace WaringSProblemVariantsCanonicalLaneLean

-- Root module

end WaringSProblemVariantsCanonicalLaneLean
end HautevilleHouse