import WaringSProblemVariantsCanonicalLaneLean.Basic
import WaringSProblemVariantsCanonicalLaneLean.AdmissibleClass
import WaringSProblemVariantsCanonicalLaneLean.BridgeLemmas
import WaringSProblemVariantsCanonicalLaneLean.GateLemmas
import WaringSProblemVariantsCanonicalLaneLean.FinalTheorem
import WaringSProblemVariantsCanonicalLaneLean.WaringSProblemPackage
import WaringSProblemVariantsCanonicalLaneLean.SumOfPowersPackage
import WaringSProblemVariantsCanonicalLaneLean.MinimalRepresentationPackage
import WaringSProblemVariantsCanonicalLaneLean.AsymptoticBoundsPackage
import WaringSProblemVariantsCanonicalLaneLean.PolynomialMethodPackage
import WaringSProblemVariantsCanonicalLaneLean.EndpointClassification

namespace HautevilleHouse
namespace WaringSProblemVariantsCanonicalLaneLean

end WaringSProblemVariantsCanonicalLaneLean
end HautevilleHouse